services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "${SERVER_HOST_PORT:-8080}:8080"
        container_name: avito-backend-container
        networks:
            - app-network
        restart: unless-stopped

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                VITE_API_URL: ${FRONTEND_API_URL:-http://localhost:8080/api/v1/}
        ports:
            - "${FRONTEND_HOST_PORT:-3000}:80"
        container_name: avito-frontend-container
        depends_on:
            - server
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        driver: bridge